
services:
  postgres:
    container_name: task-management-db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'task-management'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
